### PR TITLE
To/#64 proccess pfgrid prior to conversion

### LINKED ISSUE #63: Accessing UUIDS by ids is unsafe for non-unique ids
When accessing UUIDS by a non-unique id I might get a wrong UUID and afterwards wrong objects without noticing it.

### LINKED ISSUE #64: Process PowerFactoryGridSchema before conversion
Process the automatically generated `PowerFactoryGrid` before conversion to build up more custom classes. Do Option checking and unpacking in initial conversion for more readable and flexible code on the actual PSDM conversion.

### PR DESCRIPTION
**Pull request by t-ober**
Resolves #64 
Resolves #63 

Okay I did some refactoring:

# Option unpacking into custom classes

I didn't like the mixing of all the Option checking within the actual conversion methods. I decided to more or less just unpack the schema generated grid (now `GridModel`) into a custom `GridModel` 

Pros: 
- divide responsibilities -> Option checking / Conversion
- doubles as conversion fail fast check (if there is a None where i need a value i can throw the conversion at initialization phase)
- much more flexible code because of custom classes for the grid models (shared class relations, class methods and stuff like that)

Cons:
- work
- you tell me (or please don't 😂)

# Revoke UUID -> ID mapping aka Sneaked in a var - Please don't kill me 😨 

I  scratched the UUID -> ID mapping stuff as it was actually pretty useless. Since i can only link between elements by their ids (e.g. a line only knows about the ids of the node it's connected to) I need to make sure that these are unique anyways. As I get the ids from their directory in memory they should be, but to be sure I check every id against all previously seen ids when instantiating an object. (For that i store all IDs in a var)

Also shamelessly stealed some of the Code from our lord and savior @ckittl

### CODE REVIEW

File: src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala [hunk 1]
```diff
@@ -8,95 +8,61 @@ package edu.ie3.powerFactory2psdm.converter
...
     */
   def convertNode(
-      nodeUUID: UUID,
-      UUID2node: Map[UUID, Nodes],
+      id: String,
+      id2node: Map[String, Node],
       subnet: Subnet
   ): NodeInput = {
-    val pfNode = UUID2node(nodeUUID)
+    val node = id2node(id)
```
Comment (johanneshiry) [inline src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala:34]: Unsafe! Throws Exception if `id` is not in map. 
I know that this is impossible as of `GridConverter:35` but its not clear visible at this point and if somebody modifies `GridConverter:35` in the future, this might explode here ... -> not good 

Additionally, you have duplicate data here (`node` contains its `id`) 

Suggestion: 

```
  def convertNode(
      node: Node,
      subnet: Subnet
  ): NodeInput = {
    val subnetId = subnet.id
    val vTarget = Quantities.getQuantity(node.vTarget, PU)
    val geoPosition: Point = CoordinateConverter.convert(node.lat, node.lon)
    val voltLvl = subnet.voltLvl
    val slack = isSlack(node)
    new NodeInput(
      UUID.randomUUID(),
      node.id,
      OperatorInput.NO_OPERATOR_ASSIGNED,
      OperationTime.notLimited(),
      vTarget,
      slack,
      geoPosition,
      voltLvl,
      subnetId
    )
  }
```

File: src/main/scala/edu/ie3/powerFactory2psdm/converter/GridConverter.scala [hunk 2]
```diff
@@ -8,52 +8,50 @@ package edu.ie3.powerFactory2psdm.converter
...
     */
   def convertNodesOfSubnet(
       subnet: Subnet,
-      uuid2node: Map[UUID, Nodes]
+      id2node: Map[String, Node]
   ): List[NodeInput] =
-    subnet.nodeUuids
-      .map(nodeUuid => NodeConverter.convertNode(nodeUuid, uuid2node, subnet))
+    subnet.nodeIds
+      .map(nodeId => NodeConverter.convertNode(nodeId, id2node, subnet))
```
Comment (johanneshiry) [inline src/main/scala/edu/ie3/powerFactory2psdm/converter/GridConverter.scala:54]: In conjunction with my proposal for `NodeConverter`

```suggestion
 id2node
      .filter { case (nodeId, _) => subnet.nodeIds.contains(nodeId) }.map {
      case (_, node) => NodeConverter.convertNode(node, subnet)
    }.toList
```

File: src/main/scala/edu/ie3/powerFactory2psdm/converter/SubnetBuilder.scala [hunk 3]
```diff
@@ -31,19 +32,19 @@ object SubnetBuilder extends LazyLogging {
...
     *
     * @param gridGraph the built grid graph represented by the UUIDS of the nodes and the lines connecting them
-    * @param uuid2Node the mapping between UUID and the corresponding node
+    * @param id2Node the mapping between UUID and the corresponding node
     * @return the list of all subnets of the grid
     */
   def buildSubnets(
-      gridGraph: Multigraph[UUID, DefaultEdge],
-      uuid2Node: Map[UUID, Nodes]
+      gridGraph: Multigraph[String, DefaultEdge],
```
Comment (johanneshiry) [inline src/main/scala/edu/ie3/powerFactory2psdm/converter/SubnetBuilder.scala:39]: In conjunction with my proposal for `GridGraphBuilder`

```suggestion
      gridGraph: AsUnmodifiableGraph[String, DefaultEdge],
```

File: src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala [hunk 4]
```diff
@@ -8,95 +8,61 @@ package edu.ie3.powerFactory2psdm.converter
...
     val subnetId = subnet.id
-    val vTarget = pfNode.vtarget
-      .map(Quantities.getQuantity(_, PU))
-      .getOrElse(Quantities.getQuantity(1d, PU))
-    val geoPosition: Point =
-      CoordinateConverter.convert(pfNode.GPSlat, pfNode.GPSlon)
+    val vTarget = Quantities.getQuantity(node.vTarget, PU)
```
[the remark this answers is not in the document]
Comment (t-ober) [reply src/main/scala/edu/ie3/powerFactory2psdm/converter/NodeConverter.scala:36]: image

File: src/main/scala/edu/ie3/powerFactory2psdm/converter/GridConverter.scala [hunk 5]
```diff
@@ -8,52 +8,50 @@ package edu.ie3.powerFactory2psdm.converter
...
+  RawGridModel
 }
-import edu.ie3.powerFactory2psdm.util.GridPreparator
-
-import java.util.UUID
 
 /**
   * Functionalities to transform an exported and then parsed PowerFactory grid to the PSDM.
   */
 case object GridConverter {
```
[the remark this answers is not in the document]
Comment (t-ober) [reply src/main/scala/edu/ie3/powerFactory2psdm/converter/GridConverter.scala:20]: Cool stuff! Will add this as an issue to address it later on

File: src/main/scala/edu/ie3/powerFactory2psdm/model/powerfactory/GridModel.scala [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+        )
+      case trafo2w: Trafos2w =>
+        trafo2w.id.getOrElse(
+          throw MissingParameterException(
+            s"Transformer $trafo2w has no defined id"
+          )
+        )
+    }
+    val duplicateIds =
+      modelIds.groupBy(identity).collect { case (x, List(_, _, _*)) => x }
```
Comment (johanneshiry) [inline src/main/scala/edu/ie3/powerFactory2psdm/model/powerfactory/GridModel.scala:61]: Maybe...?

```suggestion
    val duplicateIds =
      modelIds.toSet
```

**Review by johanneshiry — CHANGES_REQUESTED** [review]
Only one last comment :)

File: src/main/scala/edu/ie3/powerFactory2psdm/model/powerfactory/GridModel.scala (hunk 6 above)
Comment (t-ober) [reply src/main/scala/edu/ie3/powerFactory2psdm/model/powerfactory/GridModel.scala:61]: Yes I expected that 😂  
Well I thought about sets but how would you sensibly extract those duplicated ids afterwards? 

I could go

```
    if (modelIds.toSet.size < modelIds.size) {
      val duplicateIds =
        modelIds.groupBy(identity).collect { case (x, List(_, _, _*)) => x }
      throw GridConfigurationException(
        s"Can't build grid as there are grid elements with duplicated ids: $duplicateIds"
      )
    }
```
but I thought building the set would be similarly expensive as extracting the duplicates and in the case I have any duplicates i would have to get them someway anyways so I just did it right away. 

Is there a simpler way that I miss?

Comment (johanneshiry) [reply src/main/scala/edu/ie3/powerFactory2psdm/model/powerfactory/GridModel.scala:61]: Well there is still a way to go with a `Set` or `Seq.distinct`:

```
scala> val duplicates = List(1, 2, 3, 3)
val duplicates: List[Int] = List(1, 2, 3, 3)

scala> val uniques = duplicates.distinct
val uniques: List[Int] = List(1, 2, 3)

scala> val duplicatesOnly = duplicates.diff(duplicates.distinct)
val duplicatesOnly: List[Int] = List(3)
```

**Review by johanneshiry — APPROVED** [review]
