### PR TITLE
fix test

### LINKED ISSUE #212: Fix failing test due to unintentional push on master
P.S. restrictions weren't applied to administrators. This is adjsuted now.

### PR DESCRIPTION
**Pull request by t-ober**
Resolves #212 and #211 (already resolved due to push to master)

### CODE REVIEW

File: src/test/scala/edu/ie3/powerFactory2psdm/common/ConverterTestData.scala [hunk 1]
```diff
@@ -688,8 +688,8 @@ object ConverterTestData extends LazyLogging {
     "someSwitch" -> ConversionPair(
       Switch(
         "someSwitch",
-        getNodePair("someNode").input.id,
-        getNodePair("someSlackNode").input.id,
+        getNodePair("someNode").input.unsafeId,
```
Comment (sebastian-peter) [inline src/test/scala/edu/ie3/powerFactory2psdm/common/ConverterTestData.scala:691]: Maybe indicate within documentation of `Switch` that you need the unsafe id here?

**Review by sebastian-peter — APPROVED** [review]
From my side good to go, just maybe add a hint to prevent such errors from happening again?
